### ISSUE TITLE
node-sass error please help

### ISSUE THREAD

**Issue by victorkamoto** [creativetimofficial/blk-design-system-react#11]
[3/4] Linking dependencies...
warning " > react-bootstrap-switch@15.5.3" has unmet peer dependency "prop-types@^15.5.0".
[4/4] Building fresh packages...
[1/3] ⠄ node-sass                                                                                                       [-/3] ⠄ waiting...                                                                                                      error C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Vic\\Desktop\\UI\\blk-design-system-react-master\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.5.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (C:\\Users\\Vic\\Desktop\\UI\\blk-design-system-react-master\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (C:\\Users\\Vic\\Desktop\\UI\\blk-design-system-react-master\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (C:\\Users\\Vic\\Desktop\\UI\\blk-design-system-react-master\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at C:\\Users\\Vic\\Desktop\\UI\\blk-design-system-react-master\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at C:\\Users\\Vic\\Desktop\\UI\\blk-design-system-react-master\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at C:\\Users\\Vic\\Desktop\\UI\\blk-design-system-react-master\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:165:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\Vic\AppData\Local\Programs\Python\Python37-32\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Vic\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:290:12)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Vic\\Desktop\\UI\\blk-design-system-react-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Vic\Desktop\UI\blk-design-system-react-master\node_modules\node-sass
gyp ERR! node -v v12.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by victorkamoto** [comment]
Copy the assets folder instead...
